//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHang
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string ChatLieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> DonGiaBan { get; set; }
    }
}
