//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_giang
    {
        public string id_bai_giang { get; set; }
        public int noi_dung_bg { get; set; }
        public System.DateTime thoi_gian_bg { get; set; }
        public int luot_xem { get; set; }
        public int sl_Like_BG { get; set; }
        public string id_nguoi_dung { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
