//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_viet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bai_viet()
        {
            this.binh_luan = new HashSet<binh_luan>();
        }
    
        public string noi_dung { get; set; }
        public string ID_bai_viet { get; set; }
        public int sl_Like { get; set; }
        public System.DateTime thoi_gian_dang_bai { get; set; }
        public string id_nguoi_dung { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<binh_luan> binh_luan { get; set; }
    }
}
