//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class binh_luan
    {
        public int noi_dung_binh_luan { get; set; }
        public int ID_BL { get; set; }
        public int sl_Like_BL { get; set; }
        public int thoi_gian_BL { get; set; }
        public string ID_bai_viet { get; set; }
    
        public virtual bai_viet bai_viet { get; set; }
    }
}
