//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet
    {
        public System.DateTime thoi_gian_nop { get; set; }
        public double diem { get; set; }
        public string id_nguoi_dung { get; set; }
        public string id_de_thi { get; set; }
    
        public virtual De_Thi De_Thi { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
