//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuoc_thi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuoc_thi()
        {
            this.nguoi_dung = new HashSet<nguoi_dung>();
        }
    
        public string ID_CT { get; set; }
        public string tieu_de { get; set; }
        public string the_le { get; set; }
        public System.DateTime thoi_gian_BDCT { get; set; }
        public System.DateTime thoi_gian_KTCT { get; set; }
        public int sl_nguoi_tham_gia { get; set; }
        public string id_de_thi { get; set; }
    
        public virtual De_Thi De_Thi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nguoi_dung> nguoi_dung { get; set; }
    }
}
