//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTTKHTEntities : DbContext
    {
        public PTTKHTEntities()
            : base("name=PTTKHTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bai_giang> bai_giang { get; set; }
        public virtual DbSet<bai_viet> bai_viet { get; set; }
        public virtual DbSet<binh_luan> binh_luan { get; set; }
        public virtual DbSet<cap_bac> cap_bac { get; set; }
        public virtual DbSet<chi_tiet> chi_tiet { get; set; }
        public virtual DbSet<cuoc_thi> cuoc_thi { get; set; }
        public virtual DbSet<De_Thi> De_Thi { get; set; }
        public virtual DbSet<nguoi_dung> nguoi_dung { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tai_lieu> tai_lieu { get; set; }
    }
}
