//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tai_lieu
    {
        public string id_tai_lieu { get; set; }
        public string noi_dung_tai_lieu { get; set; }
        public System.DateTime thoi_gian_dang { get; set; }
        public string chu_de { get; set; }
        public string id_nguoi_dung { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
