//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatLieu
    {
        public string MAVL { get; set; }
        public string TenVatLieu { get; set; }
        public string DonViTinh { get; set; }
        public double GiaNhap { get; set; }
        public double GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
    }
}
